
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  labels:
    app.kubernetes.io/part-of: ticketing
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  POSTGRES_HOST: "84.247.134.65"   # ← replace with your remote PostgreSQL IP
  POSTGRES_PORT: "5432"

  DatabaseSettings__DatabaseName: "CatalogDb"
  DatabaseSettings__CollectionName: "Events"

  Kafka__BootstrapServers: "kafka:9092"

  Redis__ConnectionString: "redis:6379"

  Serilog__WriteTo__1__Args__serverUrl: "http://seq:5341"

  Jwt__Issuer: "ticketing-identity"
  Jwt__Audience: "ticketing-services"
  Jwt__PublicKeyPath: "/app/keys/rsa-public.pem"
