apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  labels:
    app.kubernetes.io/part-of: ticketing
data:
  # ASP.NET Core
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  # MongoDB (Catalog)
  DatabaseSettings__DatabaseName: "CatalogDb"
  DatabaseSettings__CollectionName: "Events"

  # RabbitMQ (non-secret)
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"

  # Redis (Basket)
  Redis__ConnectionString: "redis:6379"

  # Seq (Centralized Logging)
  Serilog__WriteTo__1__Args__serverUrl: "http://seq:5341"

