apiVersion: v1
kind: Service
metadata:
  name: identity-api
  labels:
    app.kubernetes.io/name: identity-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ticketing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
