apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-external.yaml
  - mongo.yaml
  - redis.yaml
  - kafka.yaml
  - kafka-ui.yaml
  - seq.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - basket-deployment.yaml
  - basket-service.yaml
  - payment-deployment.yaml
  - payment-service.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - identity-deployment.yaml
  - identity-service.yaml
